import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface Dancer {
  name: string;
  city?: string | null;
  age?: number | null;
  average_score?: number | null;
  is_qualified?: boolean;
}

interface Match {
  round: string;
  position: number;
  dancer_left_name?: string;
  dancer_right_name?: string;
  winner_name?: string;
}

interface BattleExportData {
  battleName: string;
  date: string;
  location?: string;
  nominations: {
    name: string;
    dancers: Dancer[];
    matches: Match[];
  }[];
}

export function exportToPDF(data: BattleExportData) {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text(data.battleName, 20, 25);
  
  // Info
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Date: ${new Date(data.date).toLocaleDateString()}`, 20, 35);
  if (data.location) {
    doc.text(`Location: ${data.location}`, 20, 42);
  }
  
  let yPos = 55;

  data.nominations.forEach((nomination, idx) => {
    // Check if we need a new page
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }

    // Nomination header
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(nomination.name, 20, yPos);
    yPos += 10;

    // Dancers table
    if (nomination.dancers.length > 0) {
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Participants", 20, yPos);
      yPos += 5;

      autoTable(doc, {
        startY: yPos,
        head: [["#", "Name", "City", "Score", "Status"]],
        body: nomination.dancers.map((d, i) => [
          i + 1,
          d.name,
          d.city || "-",
          d.average_score?.toFixed(1) || "-",
          d.is_qualified ? "Qualified" : "-"
        ]),
        theme: "striped",
        headStyles: { fillColor: [239, 68, 68] },
        margin: { left: 20, right: 20 },
      });

      yPos = (doc as any).lastAutoTable.finalY + 15;
    }

    // Matches table
    if (nomination.matches.length > 0) {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Battle Results", 20, yPos);
      yPos += 5;

      autoTable(doc, {
        startY: yPos,
        head: [["Round", "Match", "Red Corner", "Blue Corner", "Winner"]],
        body: nomination.matches.map((m) => [
          m.round,
          m.position,
          m.dancer_left_name || "TBD",
          m.dancer_right_name || "TBD",
          m.winner_name || "-"
        ]),
        theme: "striped",
        headStyles: { fillColor: [59, 130, 246] },
        margin: { left: 20, right: 20 },
      });

      yPos = (doc as any).lastAutoTable.finalY + 20;
    }
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated by SWITCHBOARD - Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  doc.save(`${data.battleName.replace(/\s+/g, "-").toLowerCase()}-results.pdf`);
}

export function exportToCSV(data: BattleExportData) {
  let csv = "";
  
  // Header info
  csv += `Battle: ${data.battleName}\n`;
  csv += `Date: ${new Date(data.date).toLocaleDateString()}\n`;
  if (data.location) csv += `Location: ${data.location}\n`;
  csv += "\n";

  data.nominations.forEach((nomination) => {
    csv += `--- ${nomination.name} ---\n\n`;
    
    // Dancers
    if (nomination.dancers.length > 0) {
      csv += "PARTICIPANTS\n";
      csv += "Rank,Name,City,Score,Qualified\n";
      nomination.dancers.forEach((d, i) => {
        csv += `${i + 1},${d.name},${d.city || ""},${d.average_score || ""},${d.is_qualified ? "Yes" : "No"}\n`;
      });
      csv += "\n";
    }

    // Matches
    if (nomination.matches.length > 0) {
      csv += "BATTLE RESULTS\n";
      csv += "Round,Match,Red Corner,Blue Corner,Winner\n";
      nomination.matches.forEach((m) => {
        csv += `${m.round},${m.position},${m.dancer_left_name || "TBD"},${m.dancer_right_name || "TBD"},${m.winner_name || ""}\n`;
      });
      csv += "\n";
    }
  });

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${data.battleName.replace(/\s+/g, "-").toLowerCase()}-results.csv`;
  link.click();
}